export const friendList = [
  {
    image: require("../../../assets/images/axyl.jpg"),
    name: "Axyl D. Tima-an",
    age: 22,
    gender: "Male",
    birthdate: "12/26/2001",
  },
  {
    image: require("../../../assets/images/clint.jpg"),
    name: "Clint Ivan Ybañez",
    age: 20,
    gender: "Male",
    birthdate: "04/13/2003",
  },
  {
    image: require("../../../assets/images/niko.jpg"),
    name: "Niko Herbias",
    age: 21,
    gender: "Male",
    birthdate: "10/23/2002",
  },
  {
    image: require("../../../assets/images/kj.jpg"),
    name: "Kian June Catubig",
    age: 21,
    gender: "Male",
    birthdate: "07/06/2002",
  },
  {
    image: require("../../../assets/images/john_bert.jpg"),
    name: "John Bert Decinan",
    age: 20,
    gender: "Male",
    birthdate: "05/02/2003",
  },
  {
    image: require("../../../assets/images/zild.jpg"),
    name: "Zildjan Leenor Luvindino",
    age: 20,
    gender: "Male",
    birthdate: "02/18/2003",
  },
  {
    image: require("../../../assets/images/jam.jpg"),
    name: "Jamaikha Mitucua",
    age: 21,
    gender: "Female",
    birthdate: "11/13/2002",
  },
  {
    image: require("../../../assets/images/jose.png"),
    name: "Jose Rey Alfante",
    age: 20,
    gender: "Male",
    birthdate: "07/02/2003",
  },
  {
    image: require("../../../assets/images/jolexian.png"),
    name: "Jolexian Guba",
    age: 21,
    gender: "Male",
    birthdate: "08/06/2002",
  },
  {
    image: require("../../../assets/images/jake.jpg"),
    name: "Mark Jake Lapiz",
    age: 20,
    gender: "Male",
    birthdate: "07/13/2003",
  },
];
